# version: '3.9'

# services:
#   db:
#     build: 
#       context: ./prisma/docker/mongodb-replica-set
#       args:
#        MONGO_VERSION: 6
#     restart: unless-stopped
#     ports:
#     - 27017:27017
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#       MONGODB_INITDB_DATABASE: nest
#       MONGO_REPLICA_HOST: 127.0.0.1
#       MONGO_REPLICA_PORT: 27017
#       MONGO_COMMAND: 'mongosh'
#     # healthcheck:
#     #   # Use "mongo" instead of "mongosh" before v5.0
#     #   test: ['CMD', 'mongosh', 'admin', '--port', '27017', '--eval', "db.adminCommand('ping').ok"]
#     #   interval: 5s
#     #   timeout: 2s
#     #   retries: 20  
      
# volumes:
#   mongodb_data:
#     driver: local

# networks:
#   my-network:
#     external: true

# # //Linux ou Mac
# # /etc/hosts

# # 127.0.0.1 host.docker.internal

# # //Windows
# # C:\Windows\system32\drivers\etc\hosts (bloco de notas como administrador)
# # 127.0.0.1 host.docker.internal


version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_INITDB_DATABASE: nest
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017